"""
AI Digest System — Section 3 & 4 Schemas
==========================================
Built from deep analysis of collected_api_data.json

Actual data reality discovered:
  arxiv          : 298 papers  — abstract only, no delta
  github         : 26 trending_repos (README excerpt = static boilerplate)
                   5  framework_releases (notes = raw changelog = GOLD)
                   15 new_repos (description + readme_excerpt)
  hacker_news    : 9  stories  — story_text EMPTY in most items
  huggingface    : 20 models + 20 datasets — model_card_text = very long
  semantic_scholar: 100 papers — abstract + citation count, year 2025
  stack_overflow : 18 questions — body is HTML
  rss_feeds      : 168 entries across 44 feeds — summary is richest field
  reddit         : NO DATA (status: no_data_output)

Fundamental gap per source:
  arxiv            → abstract describes the paper but NOT the novel contribution
  github trending  → pushed_at shows activity but README never says "what changed"
  github releases  → notes is a raw changelog dump, needs key-change extraction
  github new_repos → description is 1 line, README is marketing copy
  hackernews       → story_text is empty; only title + points signal relevance
  huggingface      → model_card_text is long; trending_score shows community pull
  semantic_scholar → paper may be old (year 2025), citations are the only signal
  stackoverflow    → body is HTML; the question topic reveals practitioner pain
  rss_feeds        → summary is rich but often contains boilerplate endings
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Annotated, Any, Literal, Optional, Union

from pydantic import AnyHttpUrl, BaseModel, ConfigDict, Field, field_validator, model_validator
from typing_extensions import TypedDict


# ══════════════════════════════════════════════════════════════════════════════
# SHARED ENUMS  (referenced in both sections)
# ══════════════════════════════════════════════════════════════════════════════

class SourceName(str, Enum):
    ARXIV            = "arxiv"
    GITHUB_RELEASE   = "github_release"
    GITHUB_REPO      = "github_repo"
    HACKERNEWS       = "hackernews"
    HUGGINGFACE      = "huggingface"
    REDDIT           = "reddit"
    SEMANTIC_SCHOLAR = "semantic_scholar"
    STACKOVERFLOW    = "stackoverflow"
    RSS_FEEDS        = "rss_feeds"


class NoveltyType(str, Enum):
    """
    What kind of "newness" does this item represent?
    Drives the digest section assignment and headline framing.

    NEW_RELEASE   → version bump / official release with changelog
    NEW_REPO      → repository created within last N days
    MODEL_DROP    → new model weights published on HuggingFace or announced
    BREAKTHROUGH  → paper proposes method with significant benchmark gains
    UPDATE        → incremental improvement / patch / dependency bump
    TRENDING      → existing thing suddenly spiking in community attention
    DISCUSSION    → notable community debate, question, or opinion post
    TOOL_LAUNCH   → new developer tool / SDK / library announced

    Extended values (LLMs commonly generate these — accepted and mapped to
    digest sections to avoid API-level tool-call validation failures in TOOLS mode):

    NEW_FEATURE   → new capability added to an existing framework/service
    NEW_SERVICE   → new cloud service or platform announced
    NEW_PROJECT   → new open-source project or initiative
    ARTICLE       → blog post, opinion piece, or technical write-up
    ANNOUNCEMENT  → official announcement from a company or project
    BLOG_POST     → technical blog post or tutorial
    TUTORIAL      → how-to guide or learning resource
    SECURITY_FIX  → security patch, vulnerability fix, or CVE
    DEPRECATION   → feature removal, API deprecation, EOL notice
    BENCHMARK     → performance comparison, benchmark results
    """
    NEW_RELEASE   = "new_release"
    NEW_REPO      = "new_repo"
    MODEL_DROP    = "model_drop"
    BREAKTHROUGH  = "breakthrough"
    UPDATE        = "update"
    TRENDING      = "trending"
    DISCUSSION    = "discussion"
    TOOL_LAUNCH   = "tool_launch"
    # Extended values — commonly generated by LLMs
    NEW_FEATURE   = "new_feature"
    NEW_SERVICE   = "new_service"
    NEW_PROJECT   = "new_project"
    ARTICLE       = "article"
    ANNOUNCEMENT  = "announcement"
    BLOG_POST     = "blog_post"
    TUTORIAL      = "tutorial"
    SECURITY_FIX  = "security_fix"
    DEPRECATION   = "deprecation"
    BENCHMARK     = "benchmark"


class TimeSensitivity(str, Enum):
    """How quickly does this item become stale?"""
    LOW    = "low"     # research papers, foundational tools — valid for weeks
    MEDIUM = "medium"  # new repos, trending discussions — valid for ~1 week
    HIGH   = "high"    # releases, model drops, breaking news — act today


class ImpactedAudience(str, Enum):
    ML_ENGINEERS       = "ml_engineers"
    BACKEND_DEVELOPERS = "backend_developers"
    AI_RESEARCHERS     = "ai_researchers"
    AGENT_BUILDERS     = "agent_builders"
    DEVOPS_MLOPS       = "devops_mlops"
    DATA_SCIENTISTS    = "data_scientists"
    GENERAL_DEVELOPERS = "general_developers"


class DigestSectionName(str, Enum):
    TOP_STORY          = "top_story"
    FRAMEWORK_RELEASES = "framework_releases"
    NEW_TOOLS          = "new_tools"
    MODEL_RELEASES     = "model_releases"
    RESEARCH           = "research"
    COMMUNITY_BUZZ     = "community_buzz"
    INFRASTRUCTURE     = "infrastructure"
    QUICK_LINKS        = "quick_links"


class LLMProvider(str, Enum):
    """Supported LLM providers for the application."""
    GROQ       = "groq"
    GEMINI     = "gemini"
    CEREBRAS   = "cerebras"
    TOGETHER   = "together"
    OPENROUTER = "openrouter"
    MISTRAL    = "mistral"
    DEEPSEEK   = "deepseek"
    GITHUB     = "github"
    OLLAMA     = "ollama"
    SAMBANOVA  = "sambanova"


class PublishStatus(str, Enum):
    PENDING   = "pending"
    RUNNING   = "running"
    COMPLETED = "completed"
    FAILED    = "failed"


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 3 — LANGGRAPH + LLM SCHEMAS
# ══════════════════════════════════════════════════════════════════════════════

# ─────────────────────────────────────────────────────────────────────────────
# 3A.  RAW ITEM SCHEMAS — one per actual source shape in collected_api_data.json
#
# These are NOT the FastAPI response schemas.
# These represent what is ACTUALLY in the JSON file as observed.
# The subgraph fetch_node deserializes the collected JSON into these.
# ─────────────────────────────────────────────────────────────────────────────

class RawArxivItem(BaseModel):
    """
    Actual shape: arxiv.papers[i]
    Fields present: title, authors, published, url, abstract,
                    categories, primary_category, pdf_url
    Gap: abstract describes the paper but never says what is NEW
         compared to prior work — that is the LLM's job.
    """
    title:            str
    authors:          list[str]
    published:        str           # ISO datetime string
    url:              AnyHttpUrl
    abstract:         str
    categories:       list[str]
    primary_category: str
    pdf_url:          Optional[AnyHttpUrl] = None


class RawGithubRelease(BaseModel):
    """
    Actual shape: github.data.framework_releases[i]
    Fields present: framework, repo, version, published, url, notes
    This is the HIGHEST VALUE github subtype.
    notes = raw changelog text — LLM must extract 2-3 key changes.
    Gap: notes list every commit including chore/deps bumps — noise.
    """
    framework:  str
    repo:       str
    version:    str
    published:  str
    url:        AnyHttpUrl
    notes:      str     # Raw changelog dump — often contains 20+ lines of noise


class RawGithubTrendingRepo(BaseModel):
    """
    Actual shape: github.data.trending_repos[i]
    Fields present: name, stars, forks, description, language,
                    url, pushed_at, topics, readme_excerpt
    Gap: readme_excerpt is STATIC installation/marketing copy.
         pushed_at tells us it was active but NOT what changed.
         LLM must infer "why trending now" from description + topics.
    """
    name:          str           # "owner/repo" format
    stars:         int
    forks:         int
    description:   Optional[str] = None
    language:      Optional[str] = None
    url:           AnyHttpUrl
    pushed_at:     str           # ISO datetime
    topics:        list[str]     = Field(default_factory=list)
    readme_excerpt: Optional[str] = None  # Static boilerplate — low value


class RawGithubNewRepo(BaseModel):
    """
    Actual shape: github.data.new_repos[i]
    Fields present: name, stars, created, description, url, readme_excerpt
    Gap: No version/release info — just a new project announcement.
         readme_excerpt may be the only signal of what it actually does.
    """
    name:          str
    stars:         int
    created:       str           # ISO datetime
    description:   Optional[str] = None
    url:           AnyHttpUrl
    readme_excerpt: Optional[str] = None


class RawHackerNewsItem(BaseModel):
    """
    Actual shape: hacker_news.stories[i]
    Fields present: category, title, author, points, num_comments,
                    url, story_url, created_at, story_text, object_id
    CRITICAL GAP: story_text is EMPTY for most items in the actual data.
    The LLM only has: title + points + num_comments to judge relevance.
    community_signal = points * log(1 + num_comments) is the key quality signal.
    """
    category:     str
    title:        str
    author:       str
    points:       int
    num_comments: int
    url:          Optional[AnyHttpUrl] = None    # External link (often empty)
    story_url:    AnyHttpUrl                     # HN thread URL — always present
    created_at:   str
    story_text:   str = ""    # Almost always empty — design around this reality
    object_id:    str


class RawHuggingFaceModel(BaseModel):
    """
    Actual shape: huggingface.data.models[i]
    Fields present: id, downloads, likes, trending_score, pipeline_tag,
                    last_modified, description, model_card_text, tags, url
    Gap: model_card_text is extremely long (thousands of chars).
         The LLM must extract: architecture novelty + benchmark claims + use case.
         trending_score is the key community signal — higher = more relevant.
    """
    id:               str             # "owner/model-name"
    downloads:        int
    likes:            int
    trending_score:   float
    pipeline_tag:     Optional[str]   = None
    last_modified:    str
    description:      Optional[str]   = None
    model_card_text:  Optional[str]   = None   # Very long — truncate before LLM
    tags:             list[str]       = Field(default_factory=list)
    url:              AnyHttpUrl


class RawHuggingFaceDataset(BaseModel):
    """
    Actual shape: huggingface.data.datasets[i]
    Same fields as model but no pipeline_tag.
    """
    id:              str
    downloads:       int
    likes:           int
    trending_score:  float
    description:     Optional[str]  = None
    model_card_text: Optional[str]  = None
    last_modified:   str
    tags:            list[str]      = Field(default_factory=list)
    url:             AnyHttpUrl


class RawSemanticScholarPaper(BaseModel):
    """
    Actual shape: semantic_scholar.papers[i]
    Fields present: query, title, year, citations, url, authors,
                    abstract, publication_date, pdf_url, publication_types
    Gap: Papers here are from 2025 (not today). citations is the only
         quality signal. The LLM must assess: is this paper foundational
         enough to mention despite its age? Use citations as threshold.
    """
    query:            str            # The search query that found this paper
    title:            str
    year:             int
    citations:        int            # High citations = established importance
    url:              AnyHttpUrl
    authors:          list[str]
    abstract:         str
    publication_date: Optional[str]  = None
    pdf_url:          Optional[AnyHttpUrl] = None
    publication_types: list[str]     = Field(default_factory=list)


class RawStackOverflowQuestion(BaseModel):
    """
    Actual shape: stack_overflow.questions[i]
    Fields present: title, score, answer_count, view_count, tags,
                    url, creation_date, last_activity_date, body
    Gap: body contains HTML tags — must be stripped before LLM.
         Most questions here have score=0 (not voted up yet).
         The LLM must infer: does this question represent a common
         practitioner pain point? view_count > 50 = notable.
    """
    title:              str
    score:              int
    answer_count:       int
    view_count:         int
    tags:               list[str]
    url:                AnyHttpUrl
    creation_date:      int      # Unix timestamp
    last_activity_date: int      # Unix timestamp
    body:               str      # HTML — strip tags before LLM consumption


class RawRSSEntry(BaseModel):
    """
    Actual shape: rss_feeds.entries[i]
    Fields present: feed, section, title, link, published, summary
    summary is the RICHEST content field in the whole dataset — often
    contains 2000+ chars of actual article body.
    Gap: some summaries have WordPress/newsletter boilerplate at the end.
    section values observed: 'Company Blogs', 'Framework Blogs',
    'Agentic Releases', 'Backend Releases', 'ML Core Releases',
    'Newsletters', 'MLOps Blogs', 'Research Blogs', etc.
    """
    feed:      str           # Feed name e.g. "HuggingFace Blog"
    section:   str           # Section category e.g. "Company Blogs"
    title:     str
    link:      AnyHttpUrl
    published: str           # RFC 822 or ISO date string
    summary:   str           # Best content signal — often full article excerpt


class RawRedditPost(BaseModel):
    """
    Actual shape: reddit.posts[i]
    Fields present in current tests: subreddit, title, author, score, num_comments,
                    url, permalink, created_utc, selftext, is_self, post_id
                    optionally top_comments when enrichment succeeds.
    """
    subreddit:    str
    title:        str
    author:       str
    score:        int
    num_comments: int
    url:          Optional[AnyHttpUrl] = None
    permalink:    AnyHttpUrl
    created_utc:  float
    selftext:     str = ""
    is_self:      bool = False
    post_id:      str
    top_comments: list[str] = Field(default_factory=list)


# Stronger typing for graph-state raw_items while still allowing mixed sources.
RawSourceItem = Union[
    RawArxivItem,
    RawGithubRelease,
    RawGithubTrendingRepo,
    RawGithubNewRepo,
    RawHackerNewsItem,
    RawHuggingFaceModel,
    RawHuggingFaceDataset,
    RawRedditPost,
    RawSemanticScholarPaper,
    RawStackOverflowQuestion,
    RawRSSEntry,
]


# ─────────────────────────────────────────────────────────────────────────────
# 3B.  NORMALIZED ITEM — unified contract after source-specific parsing
#      All subgraph normalize_nodes produce this before sending to the LLM.
# ─────────────────────────────────────────────────────────────────────────────

class NormalizedItem(BaseModel):
    """
    Single unified shape that all LangGraph LLM nodes consume.
    Subgraph normalize_node maps each raw shape into this.

    content_for_llm is the ONLY field the LLM reads for understanding.
    It is pre-assembled by the normalize_node with source-specific logic:
      arxiv        → abstract (stripped of LaTeX)
      github_release → top 10 lines of notes (after filtering chore/deps lines)
      github_repo   → description + first 300 chars of readme_excerpt
      hackernews   → title only (story_text is empty in real data)
      huggingface  → description + first 800 chars of model_card_text
      semantic_scholar → abstract
      stackoverflow → title + HTML-stripped body (truncated to 600 chars)
      rss_feeds    → summary (truncated to 1200 chars, boilerplate stripped)
    """
    # Identity
    id:           str         = Field(..., description="<source>:<unique_key>")
    source:       SourceName
    title:        str         = Field(..., min_length=3, max_length=512)
    url:          AnyHttpUrl
    published_at: datetime

    # Content assembled for LLM — NOT raw content
    model_config = ConfigDict(str_strip_whitespace=True, validate_assignment=True)

    content_for_llm: str = Field(
        ...,
        min_length=10,
        max_length=2400,
        description=(
            "Pre-assembled content for LLM consumption. "
            "Source-specific: abstracts for papers, stripped changelogs for releases, "
            "cleaned summaries for RSS. Never raw HTML or full README."
        )
    )

    # Source-specific quality signals (used by fast-fail and LLM prompts)
    quality_signals: dict[str, Any] = Field(
        default_factory=dict,
        description=(
            "Source-specific numeric signals passed to LLM as context hints. "
            "arxiv: {} | "
            "github_release: {lines_in_notes: int, is_major_version: bool} | "
            "github_repo: {stars: int, pushed_at: str, is_new: bool} | "
            "hackernews: {points: int, num_comments: int} | "
            "huggingface: {trending_score: float, downloads: int, likes: int} | "
            "semantic_scholar: {citations: int, year: int} | "
            "stackoverflow: {score: int, answer_count: int, view_count: int} | "
            "rss_feeds: {section: str, feed: str, summary_length: int}"
        )
    )

    days_old: float = Field(
        default=0.0, ge=0.0,
        description="How many days since published_at. Used in fast-fail and LLM prompts."
    )


# ─────────────────────────────────────────────────────────────────────────────
# 3C.  FAST-FAIL FILTER SCHEMA
#      Applied BEFORE any LLM call. Cheap rule-based drop.
#      Based on actual data issues observed.
# ─────────────────────────────────────────────────────────────────────────────

class FastFailVerdict(str, Enum):
    PASS         = "pass"
    DROP_STALE   = "drop_stale"       # days_old > threshold
    DROP_EMPTY   = "drop_empty"       # content_for_llm < 20 chars
    DROP_NOISE   = "drop_noise"       # matches noise pattern (dev/nightly/trunk)
    DROP_OFFTOPIC = "drop_offtopic"   # clearly irrelevant (HR, career advice)
    DROP_LOWSIG  = "drop_low_signal"  # hackernews points=0, SO score<0, etc.


class FastFailResult(BaseModel):
    """
    Per-item output of the fast-fail filter node.
    This runs synchronously on all items BEFORE the LLM is invoked.

    Thresholds by source:
      arxiv            → days_old > 7  = DROP_STALE
      github_release   → never drop (always fresh by definition)
      github_repo      → days_old > 3 for trending, > 1 for new_repo
      hackernews       → points < 2 = DROP_LOWSIG
      huggingface      → trending_score < 5 AND likes < 20 = DROP_LOWSIG
      semantic_scholar → citations < 5 = DROP_LOWSIG (too obscure)
      stackoverflow    → score < 0 = DROP_LOWSIG
      rss_feeds        → days_old > 5 = DROP_STALE
    """
    item_id:  str
    verdict:  FastFailVerdict
    reason:   str   = Field(..., max_length=200)
    score:    float = Field(
        default=0.0, ge=0.0, le=1.0,
        description=(
            "Pre-LLM quality estimate. "
            "Drives ordering when LLM receives the item list. "
            "Higher = shown earlier in LLM prompt context. "
            "Defaults to 0.0 for dropped items."
        )
    )


class FastFailBatch(BaseModel):
    """Output of the fast_fail_node for one source."""
    source:  SourceName
    passed:  list[NormalizedItem]
    dropped: list[FastFailResult]
    pass_rate: float = Field(ge=0.0, le=1.0)


# ─────────────────────────────────────────────────────────────────────────────
# 3D.  LLM OUTPUT SCHEMAS — INSTRUCTOR-ENFORCED
#      These solve the fundamental gap.
# ─────────────────────────────────────────────────────────────────────────────

class RelevanceAssessment(BaseModel):
    """
    Step 1 LLM judgment: is this item worth including at all?
    Instructor enforces this. Retry up to 3× on schema violation.

    Interest domain the LLM must use:
      KEEP: agentic frameworks (LangChain, LangGraph, CrewAI, AutoGen, Agno,
            BrowserUse, Dify, LlamaIndex), backend/serving (FastAPI, BentoML,
            vLLM, Ray, SGLang, Triton), inference runtimes (llama.cpp, Ollama),
            vector DBs, new LLM/VLM model releases, infrastructure updates.
      DROP: beginner tutorials, HR/career posts, pure marketing, papers with
            no relevance to above frameworks, SO questions about basic Python.
    """
    item_id:         str   = Field(default="", description="Must match NormalizedItem.id exactly")
    is_relevant:     bool  = True    # Default True: when in doubt, keep the item
    relevance_score: Annotated[float, Field(ge=0.0, le=1.0)] = Field(
        default=0.5,
        description=(
            "0.0 = completely off-topic. "
            "0.5 = tangentially related. "
            "1.0 = directly about agentic/backend/ML frameworks."
        )
    )
    reject_reason: Optional[str] = Field(
        None, max_length=200,
        description="Required if is_relevant=False. Be specific: 'beginner Python tutorial', 'HR announcement', etc."
    )

    @model_validator(mode="before")
    @classmethod
    def _fix_id_field(cls, data: Any) -> Any:
        """LLMs often return 'id' instead of 'item_id' — auto-fix it."""
        if isinstance(data, dict):
            # Rename 'id' -> 'item_id' if item_id is missing
            if "item_id" not in data and "id" in data:
                data["item_id"] = data.pop("id")
            # Clamp relevance_score to [0, 1]
            score = data.get("relevance_score")
            if isinstance(score, (int, float)):
                data["relevance_score"] = max(0.0, min(1.0, float(score)))
            # Ensure reject_reason is set when is_relevant=False
            if not data.get("is_relevant") and not data.get("reject_reason"):
                data["reject_reason"] = "no reason provided by LLM"
        return data


class InsightExtraction(BaseModel):
    """
    THE CORE SCHEMA that fixes the fundamental gap.
    Forces the LLM to extract delta + impact, not just summarize.

    Source-specific guidance baked into field descriptions:

    For github_release:
      change_summary  = the 2-3 meaningful changes from the notes field
                        (ignore all 'chore(deps): bump' lines)
      significance    = what this version enables that the last didn't

    For github_repo (trending):
      change_summary  = why this repo is trending NOW (context clue: pushed_at)
      significance    = what problem it solves that existing tools don't

    For github_repo (new):
      change_summary  = what this new project does (from description + readme)
      significance    = what gap it fills in the ecosystem

    For arxiv / semantic_scholar:
      change_summary  = the core novel contribution in plain English
      significance    = practical implication for engineers (not researchers)

    For hackernews (story_text is often EMPTY):
      change_summary  = infer from title alone what this is about
      significance    = why the HN community found this worth sharing

    For huggingface:
      change_summary  = what architecture/training novelty this model has
      significance    = how it compares to existing models (benchmark claims)

    For rss_feeds:
      change_summary  = what specifically happened (new release, new feature, etc.)
      significance    = impact on practitioners building with these frameworks

    For stackoverflow:
      change_summary  = what problem practitioners are hitting
      significance    = how common/important is this pain point
    """

    item_id: str = Field(..., description="Must match NormalizedItem.id exactly")

    # ── WHAT CHANGED ──────────────────────────────────────────────────────────
    change_summary: str = Field(
        ...,
        min_length=20,
        max_length=500,
        description=(
            "What is NEW or DIFFERENT about this item. "
            "NOT a restatement of the title. "
            "For releases: the 2-3 key functional changes (skip chore/deps bumps). "
            "For repos: what problem it solves or why it is trending now. "
            "For papers: the core novel contribution in one sentence. "
            "For HN/SO: what the community is reacting to or struggling with. "
            "Write in past tense: 'Added X', 'Released Y', 'Fixed Z'. "
            "IMPORTANT: Keep under 300 characters."
        )
    )

    # ── WHY IT MATTERS ────────────────────────────────────────────────────────
    significance: str = Field(
        ...,
        min_length=20,
        max_length=500,
        description=(
            "Why a practitioner building LLM/agent applications should care. "
            "Must be practical, not academic. "
            "Start with the consequence: 'This means you can now...', "
            "'Developers using X will see...', 'This fixes the problem of...'. "
            "Never just restate change_summary. "
            "IMPORTANT: Keep under 300 characters."
        )
    )

    # ── CATEGORIZATION ────────────────────────────────────────────────────────
    # NOTE: Using plain `str` instead of `NoveltyType` enum here because this
    # model is used as a tool-call schema in TOOLS mode (Groq, Cerebras, etc.).
    # The API provider validates enum values BEFORE Pydantic sees them, so if
    # the LLM invents a value like "new_model" that isn't in the enum, the API
    # returns a 400 error and our validators never run. Using `str` lets the
    # API accept any value, and the `_coerce_novelty_type` validator below
    # normalizes it to a valid NoveltyType enum value.
    novelty_type: str = Field(
        ...,
        description=(
            "Pick the MOST SPECIFIC type from: "
            "new_release (version bump/official release), "
            "new_repo (newly created repository), "
            "model_drop (new model weights), "
            "breakthrough (paper with significant results), "
            "update (incremental improvement/patch), "
            "trending (spiking in community attention), "
            "discussion (community debate/opinion), "
            "tool_launch (new dev tool/SDK/library), "
            "new_feature (new capability in existing framework/service), "
            "new_service (new cloud service/platform), "
            "new_project (new open-source project), "
            "article (blog post/technical write-up), "
            "announcement (official company announcement), "
            "blog_post (technical blog), "
            "tutorial (how-to guide), "
            "security_fix (security patch/CVE), "
            "deprecation (feature removal/EOL), "
            "benchmark (performance comparison)."
        )
    )

    # NOTE: Using list[str] instead of list[ImpactedAudience] for the same
    # reason as novelty_type — API-level enum validation causes 400 errors.
    # The `_coerce_impacted_audience` validator normalizes values below.
    impacted_audience: list[str] = Field(
        ...,
        min_length=1,
        max_length=3,
        description=(
            "Who benefits most. Pick 1-3 from: "
            "ml_engineers, backend_developers, ai_researchers, "
            "agent_builders, devops_mlops, data_scientists, general_developers. "
            "Be specific — not 'everyone'."
        )
    )

    # NOTE: Using str instead of TimeSensitivity for the same reason.
    # The `_coerce_time_sensitivity` validator normalizes values below.
    time_sensitivity: str = Field(
        ...,
        description=(
            "Pick one of: high, medium, low. "
            "HIGH: release today, model drop, security fix — act now. "
            "MEDIUM: new repo, trending discussion — relevant this week. "
            "LOW: research paper, foundational concept — reference material."
        )
    )

    # ── ACTIONABLE INSIGHT ────────────────────────────────────────────────────
    actionable_insight: str = Field(
        ...,
        min_length=10,
        max_length=200,
        description=(
            "Concrete thing the reader can DO with this information. "
            "Examples: "
            "'pip install langchain-core==1.2.22 to get the path validation fix', "
            "'Try the 4B model locally with ollama run nemotron-nano-4b', "
            "'Watch this repo — it addresses the agent memory problem directly'. "
            "If nothing actionable, write what to watch for."
        )
    )

    # ── OPTIONAL CONFIDENCE ───────────────────────────────────────────────────
    confidence: Annotated[float, Field(ge=0.0, le=1.0)] = Field(
        default=0.8,
        description=(
            "LLM self-confidence in this extraction. "
            "Set low (< 0.6) if content_for_llm was sparse (e.g., HN with empty story_text)."
        )
    )

    # ── VALIDATORS to auto-fix common LLM output issues ──────────────────────
    @field_validator("novelty_type", mode="before")
    @classmethod
    def _coerce_novelty_type(cls, v: Any) -> Any:
        """Normalize any LLM-generated novelty_type string to a valid NoveltyType value.

        Since novelty_type is now `str` (not `NoveltyType` enum) to prevent
        API-level 400 errors in TOOLS mode, this validator is the primary
        normalization mechanism. It maps known variants and unknowns to valid
        enum value strings so downstream code can safely convert to NoveltyType.
        """
        if isinstance(v, str):
            # Normalize to lowercase for case-insensitive matching
            v_lower = v.lower().strip()
            valid = {e.value for e in NoveltyType}
            if v_lower in valid:
                return v_lower
            # Extended mapping for edge-case LLM outputs
            _mapping = {
                "research_paper": "breakthrough",
                "paper": "breakthrough",
                "research": "breakthrough",
                "release": "new_release",
                "repo": "new_repo",
                "repository": "new_repo",
                "model": "model_drop",
                "model_release": "model_drop",
                "new_model": "model_drop",
                "model_launch": "model_drop",
                "model_announcement": "model_drop",
                "trend": "trending",
                "discuss": "discussion",
                "debate": "discussion",
                "conversation": "discussion",
                "tool": "tool_launch",
                "sdk": "tool_launch",
                "library": "tool_launch",
                "feature": "new_feature",
                "service": "new_service",
                "project": "new_project",
                "post": "article",
                "blog": "blog_post",
                "guide": "tutorial",
                "howto": "tutorial",
                "how_to": "tutorial",
                "security": "security_fix",
                "patch": "update",
                "fix": "update",
                "bug_fix": "update",
                "bugfix": "update",
                "breaking_change": "deprecation",
                "breaking": "deprecation",
                "perf": "benchmark",
                "performance": "benchmark",
                "comparison": "benchmark",
            }
            return _mapping.get(v_lower, "update")
        return v

    @field_validator("time_sensitivity", mode="before")
    @classmethod
    def _coerce_time_sensitivity(cls, v: Any) -> Any:
        """Map unknown time_sensitivity values to MEDIUM."""
        if isinstance(v, str):
            valid = {e.value for e in TimeSensitivity}
            if v not in valid:
                return "medium"
        return v

    @field_validator("impacted_audience", mode="before")
    @classmethod
    def _coerce_impacted_audience(cls, v: Any) -> Any:
        """Ensure impacted_audience is a list and filter invalid values."""
        if isinstance(v, str):
            v = [v]
        if isinstance(v, list):
            valid = {e.value for e in ImpactedAudience}
            cleaned = [x for x in v if x in valid]
            return cleaned if cleaned else ["ml_engineers"]
        return v

    @model_validator(mode="before")
    @classmethod
    def _fix_and_truncate(cls, data: Any) -> Any:
        """Auto-fix common LLM output issues so free-tier LLMs never crash the batch.

        Handles ALL known failure modes:
        1. Missing 'item_id' / 'id' rename
        2. Missing required fields → fill with safe defaults
        3. Enum-like values in paragraph fields → move to correct field
           (e.g. significance="high" → time_sensitivity="high", significance=default)
        4. Strings shorter than min_length → pad to meet constraint
        5. Strings longer than max_length → truncate
        """
        if isinstance(data, dict):
            # ── 1. Rename 'id' -> 'item_id' ──────────────────────────────
            if "item_id" not in data and "id" in data:
                data["item_id"] = data.pop("id")
            if not data.get("item_id"):
                data["item_id"] = "unknown_item"

            # Also accept 'source_id' as an alias for 'item_id'
            if not data.get("item_id") or data["item_id"] == "unknown_item":
                if data.get("source_id"):
                    data["item_id"] = data.pop("source_id")

            # ── 2. Detect enum-like values in paragraph fields ────────────
            # LLMs (especially Cerebras gpt-oss-120b) confuse 'significance'
            # (a paragraph field) with 'time_sensitivity' (an enum: high/medium/low).
            # When significance="high", move it to time_sensitivity and reset significance.
            _ENUM_VALUES = {"high", "medium", "low", "critical", "urgent", "none"}
            for para_field in ("significance", "change_summary"):
                val = data.get(para_field)
                if isinstance(val, str) and val.strip().lower() in _ENUM_VALUES:
                    # This looks like an enum value, not a paragraph
                    if not data.get("time_sensitivity"):
                        data["time_sensitivity"] = val.strip().lower()
                    data[para_field] = ""  # will be filled by defaults below

            # ── 3. Provide defaults for missing/empty required fields ─────
            if not data.get("change_summary") or len(str(data.get("change_summary", ""))) < 20:
                # Try to use significance as fallback, but only if it's a real paragraph
                sig = data.get("significance", "")
                if isinstance(sig, str) and len(sig) >= 20:
                    data["change_summary"] = sig
                else:
                    data["change_summary"] = "No change summary provided by the LLM for this item."

            if not data.get("significance") or len(str(data.get("significance", ""))) < 20:
                data["significance"] = "Relevant to AI/ML practitioners based on automated screening."

            if not data.get("novelty_type"):
                data["novelty_type"] = "update"
            if not data.get("impacted_audience"):
                data["impacted_audience"] = ["ml_engineers"]
            if not data.get("time_sensitivity"):
                data["time_sensitivity"] = "medium"
            if not data.get("actionable_insight") or len(str(data.get("actionable_insight", ""))) < 10:
                data["actionable_insight"] = "Review the linked resource for details."

            # ── 4. Pad any remaining short strings to meet min_length ─────
            _MIN_LENGTHS = {
                "change_summary": 20,
                "significance": 20,
                "actionable_insight": 10,
            }
            for field_name, min_len in _MIN_LENGTHS.items():
                val = data.get(field_name)
                if isinstance(val, str) and 0 < len(val) < min_len:
                    # Pad the value rather than crashing
                    data[field_name] = val + " " * (min_len - len(val))

            # ── 5. Truncate overlong strings ──────────────────────────────
            _MAX_LENGTHS = {
                "change_summary": 500,
                "significance": 500,
                "actionable_insight": 200,
            }
            for field_name, max_len in _MAX_LENGTHS.items():
                val = data.get(field_name)
                if isinstance(val, str) and len(val) > max_len:
                    data[field_name] = val[: max_len - 3] + "..."
        return data


class EnrichedItem(BaseModel):
    """
    NormalizedItem + RelevanceAssessment + InsightExtraction.
    Produced by each subgraph's llm_enrich_node.
    This is the item that flows into the merger.
    """
    # From NormalizedItem
    id:              str
    source:          SourceName
    title:           str
    url:             AnyHttpUrl
    published_at:    datetime
    days_old:        float
    quality_signals: dict[str, Any] = Field(default_factory=dict)

    # From RelevanceAssessment
    is_relevant: bool = True
    relevance_score: Annotated[float, Field(ge=0.0, le=1.0)]
    reject_reason: Optional[str] = Field(
        None,
        max_length=150,
        description=(
            "Present when relevance screening rejects an item. "
            "Useful for audits and skipped-item reports."
        ),
    )

    # From InsightExtraction — the delta-aware fields
    change_summary:     str
    significance:       str
    novelty_type:       NoveltyType
    impacted_audience:  list[ImpactedAudience]
    time_sensitivity:   TimeSensitivity
    actionable_insight: str
    confidence:         float = Field(ge=0.0, le=1.0)

    # Assigned digest section (set by merger node based on novelty_type)
    digest_section: DigestSectionName = DigestSectionName.QUICK_LINKS

    # Provenance
    enriched_by:    LLMProvider = LLMProvider.GROQ
    selection_rank: int         = Field(ge=1)


class SubgraphOutput(BaseModel):
    """
    Complete output of one source subgraph.
    Contains the enriched items the LLM selected from that source.

    Budget constraints enforced here:
      rss_feeds        → max 25
      github (all)     → max 15 (releases + repos combined)
      reddit           → max  5  (but no data in current JSON)
      hackernews       → max  5
      huggingface      → max  5
      arxiv            → max  3
      stackoverflow    → max  3
      semantic_scholar → max  1  (optional, only if enabled)
    """
    source:          SourceName
    enriched_items:  list[EnrichedItem]
    total_reviewed:  int    = Field(ge=0)
    total_selected:  int    = Field(ge=0)
    fast_fail_dropped: int  = Field(ge=0)
    llm_dropped:     int    = Field(ge=0)
    model_used:      LLMProvider
    processing_ms:   float  = Field(ge=0.0)

    # Tracks if fallback LLM was used (Groq rate limit hit → Gemini)
    used_fallback:   bool   = False


# ─────────────────────────────────────────────────────────────────────────────
# 3E.  DEDUPLICATION SCHEMA
#      Cross-source dedup after all active source subgraphs complete.
# ─────────────────────────────────────────────────────────────────────────────

class DuplicatePair(BaseModel):
    """A pair of items identified as duplicates."""
    kept_id:          str
    dropped_id:       str
    similarity_score: Annotated[float, Field(ge=0.0, le=1.0)]
    merge_strategy:   Literal[
        "keep_higher_relevance",   # Keep whichever has higher relevance_score
        "keep_release_over_repo",  # github_release > github_repo for same project
        "keep_primary_source",     # rss_feeds > newsletter if same article
        "exact_id",                # Same item ID from multiple sources
        "url_match",               # Same URL from different sources
        "fuzzy_title",             # Similar title after stripping version numbers
    ]
    canonical_id:     str    # The ID that survived


class DeduplicationResult(BaseModel):
    """Output of the merger node's dedup phase."""
    unique_items:    list[EnrichedItem]
    duplicate_pairs: list[DuplicatePair] = Field(default_factory=list)
    total_before:    int = Field(ge=0)
    total_after:     int = Field(ge=0)
    total_dropped:   int = Field(ge=0)


# ─────────────────────────────────────────────────────────────────────────────
# 3F.  LANGGRAPH STATE SCHEMA
# ─────────────────────────────────────────────────────────────────────────────

class LLMMetrics(TypedDict, total=False):
    total_calls:          int
    total_tokens:         int
    groq_calls:           int
    gemini_fallback_calls: int
    cerebras_calls:       int
    together_calls:       int
    openrouter_calls:     int
    mistral_calls:        int
    deepseek_calls:       int
    failed_calls:         int
    total_retries:        int
    avg_latency_ms:       float


class DigestState(TypedDict, total=False):
    """
    Master LangGraph state. Keys added incrementally as graph executes.

    Flow:
      1. run_date / run_id set by entry node
      2. raw_items populated by each subgraph's fetch_node
      3. normalized_items populated by normalize_node
      4. fast_fail_results populated by fast_fail_node
      5. subgraph_outputs populated by llm_enrich_node (one per source, parallel)
      6. deduplication_result populated by merger_node
      7. final_digest populated by final_llm_node
      8. publish_status set by output_node
    """
    # Run metadata
    run_date:   str   # "YYYY-MM-DD"
    run_id:     str   # UUID

    # Raw data per source (keyed by SourceName value)
    raw_items:         dict[str, list[RawSourceItem]]  # Parsed + validated source items
    normalized_items:  dict[str, list[NormalizedItem]]
    fast_fail_results: dict[str, FastFailBatch]

    # Per-source enriched outputs (populated in parallel by Send() fan-out)
    subgraph_outputs:  dict[str, SubgraphOutput]

    # Merged + deduped flat list
    deduplication_result: DeduplicationResult
    merged_items:         list[EnrichedItem]           # Convenience alias

    # Final output
    final_digest:  "FinalDigestSchema"                 # Forward ref — defined below
    publish_status: PublishStatus

    # Cross-cutting telemetry
    llm_metrics: LLMMetrics
    errors:       list[str]

    # Source counts for stats section of digest
    source_raw_counts:      dict[str, int]   # {source: total_fetched}
    source_selected_counts: dict[str, int]   # {source: total_selected}


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 4 — FINAL DIGEST OUTPUT SCHEMAS
# ══════════════════════════════════════════════════════════════════════════════

# ─────────────────────────────────────────────────────────────────────────────
# 4A.  FINAL DIGEST ITEM  — the output unit the reader sees
#
# This schema FORCES the final LLM to produce insight-driven entries.
# It is NOT a summary of content — it is a curated, opinionated brief.
# ─────────────────────────────────────────────────────────────────────────────

class FinalDigestItem(BaseModel):
    """
    One item in the published digest.
    Produced by the final_llm_node from an EnrichedItem.
    The final LLM's job is to rewrite EnrichedItem fields
    into clean, readable prose for the digest audience.

    SYSTEM PROMPT GUIDANCE for the final LLM:
      - headline must NOT start with "Introducing" or "Announcing"
      - what_happened must be past tense and factual
      - why_it_matters must start with a consequence phrase
      - key_takeaway is the single most important sentence
      - action_hint is optional but preferred for releases and model drops
    """

    # Identity
    id:           str
    source:       SourceName
    novelty_type: NoveltyType
    section:      DigestSectionName
    url:          AnyHttpUrl
    published_at: datetime
    tags:         list[str] = Field(
        default_factory=list, max_length=5,
        description="2-5 short lowercase topic tags e.g. ['langchain', 'release', 'memory']"
    )

    # ── THE 4 MANDATORY INSIGHT FIELDS ────────────────────────────────────────

    headline: str = Field(
        ...,
        min_length=10,
        max_length=120,
        description=(
            "Rewritten title that tells the reader WHAT happened, not just the subject. "
            "Bad: 'LangChain Core 1.2.22'. "
            "Good: 'LangChain Core 1.2.22 patches prompt path traversal vulnerability'. "
            "Must NOT start with 'Introducing', 'Announcing', or 'New:'. "
            "Use active voice. No hype words."
        )
    )

    what_happened: str = Field(
        ...,
        min_length=20,
        max_length=400,
        description=(
            "Clear, factual change summary. Past tense. "
            "For releases: list the 2-3 functional changes (not chore/deps bumps). "
            "For repos: describe what the project does and why it appeared now. "
            "For papers: state the contribution and the benchmark result. "
            "For HN/SO: describe what the community is discussing. "
            "For model drops: describe architecture and key capabilities."
        )
    )

    why_it_matters: str = Field(
        ...,
        min_length=20,
        max_length=400,
        description=(
            "Practical impact for engineers building LLM/agent systems. "
            "Must start with a consequence phrase: "
            "'This means...', 'Developers will now...', 'This fixes...', "
            "'If you use X, this...', 'This is significant because...'. "
            "Never repeat what_happened. Never use the word 'important'."
        )
    )

    key_takeaway: str = Field(
        ...,
        min_length=15,
        max_length=160,
        description=(
            "The single most important sentence. "
            "Should be readable standalone, without the rest of the entry. "
            "Think: what would you put in a Slack message to your team?"
        )
    )

    # ── OPTIONAL FIELDS ───────────────────────────────────────────────────────

    action_hint: Optional[str] = Field(
        None,
        max_length=200,
        description=(
            "What the reader can DO right now. "
            "Only include if genuinely actionable. "
            "Examples: 'pip install langchain-core==1.2.22', "
            "'ollama run nemotron-nano-4b', "
            "'Watch this repo — it solves the agent memory problem'. "
            "Skip for discussions, research papers, community buzz."
        )
    )

    time_sensitivity: TimeSensitivity = TimeSensitivity.MEDIUM
    confidence_score: Annotated[float, Field(ge=0.0, le=1.0)] = Field(
        default=0.8,
        description="Inherited from InsightExtraction.confidence"
    )


# ─────────────────────────────────────────────────────────────────────────────
# 4B.  DIGEST SECTION
# ─────────────────────────────────────────────────────────────────────────────

class DigestSection(BaseModel):
    """
    One named section of the digest.
    Section assignment rules (from novelty_type):
      NEW_RELEASE              → FRAMEWORK_RELEASES
      NEW_REPO + TOOL_LAUNCH   → NEW_TOOLS
      MODEL_DROP               → MODEL_RELEASES
      BREAKTHROUGH             → RESEARCH
      TRENDING + DISCUSSION    → COMMUNITY_BUZZ
      UPDATE + INFRASTRUCTURE  → INFRASTRUCTURE
    """
    section:     DigestSectionName
    title:       str   # Human-readable: "🚀 Framework Releases", "🧠 Model Releases"
    emoji:       str   # Section emoji prefix
    items:       list[FinalDigestItem]
    item_count:  int   = 0

    # Section-level insight synthesized by final LLM
    section_summary: Optional[str] = Field(
        None,
        max_length=300,
        description=(
            "Optional 1-2 sentence synthesis of the section's theme. "
            "Only for sections with 3+ items. "
            "Example: 'Three agentic frameworks shipped releases this week, "
            "all focused on improved memory and tool calling.'"
        )
    )


# ─────────────────────────────────────────────────────────────────────────────
# 4C.  DIGEST METADATA
# ─────────────────────────────────────────────────────────────────────────────

class DigestMetadata(BaseModel):
    """Run-level metadata included in the digest header."""
    digest_date:        str             # "2026-03-25"
    generated_at:       datetime        = Field(default_factory=lambda: datetime.now(timezone.utc))
    total_raw_items:    int             = Field(ge=0)
    total_selected:     int             = Field(ge=0)
    sources_reviewed:   list[SourceName]
    providers_used:     list[LLMProvider]
    schema_version:     str             = "2.0"
    source_counts:      dict[str, dict[str, int]] = Field(
        default_factory=dict,
        description=(
            "Per-source stats: {source: {raw: N, selected: N, dropped: N}}. "
            "Example: {'arxiv': {'raw': 298, 'selected': 3, 'dropped': 295}}"
        )
    )


# ─────────────────────────────────────────────────────────────────────────────
# 4D.  FINAL DIGEST SCHEMA  (root model)
# ─────────────────────────────────────────────────────────────────────────────

class FinalDigestSchema(BaseModel):
    """
    Root schema for the complete digest.
    Produced by final_llm_node, consumed by render nodes.

    Section ordering (deterministic, always this order):
      1. top_story          (single best item, shown above all sections)
      2. FRAMEWORK_RELEASES
      3. MODEL_RELEASES
      4. NEW_TOOLS
      5. RESEARCH
      6. INFRASTRUCTURE
      7. COMMUNITY_BUZZ
      8. quick_links        (flat list excluding top_story; one row per unique id)
    """
    metadata:    DigestMetadata
    top_story:   Optional[FinalDigestItem] = Field(
        None,
        description=(
            "The single most important item today. "
            "Selected by final LLM based on: time_sensitivity=HIGH "
            "AND relevance_score > 0.8 AND novelty_type in "
            "[NEW_RELEASE, MODEL_DROP, BREAKTHROUGH, TOOL_LAUNCH]."
        )
    )
    sections:    list[DigestSection]
    quick_links: list[FinalDigestItem] = Field(
        default_factory=list,
        description=(
            "All selected non-top-story items as a flat list for scanning. "
            "Invariant: exclude top_story.id and keep ids unique."
        )
    )

    @property
    def all_items(self) -> list[FinalDigestItem]:
        result = []
        if self.top_story:
            result.append(self.top_story)
        for s in self.sections:
            result.extend(s.items)
        return result


# ─────────────────────────────────────────────────────────────────────────────
# 4E.  RENDER SCHEMAS — one per output format
# ─────────────────────────────────────────────────────────────────────────────

class MarkdownDigest(BaseModel):
    """
    Rendered Markdown. deterministic_template enforces exact section order.

    MARKDOWN TEMPLATE:
    ──────────────────────────────────────────────────────────────────
    # 🤖 AI/ML Daily Digest — {metadata.digest_date}

    > {metadata.total_selected} items curated from {metadata.total_raw_items} reviewed
    > Sources: {", ".join(source_counts.keys())}

    ---

    ## 🔥 Today's Top Story

    ### {top_story.headline}

    **What happened:** {top_story.what_happened}

    **Why it matters:** {top_story.why_it_matters}

    **Key takeaway:** _{top_story.key_takeaway}_

    {f"> 💡 **Action:** {top_story.action_hint}" if top_story.action_hint else ""}

    🔗 [{top_story.headline}]({top_story.url}) · `{top_story.source}` · {top_story.published_at:%Y-%m-%d}

    ---

    ## 🚀 Framework Releases

    {section_summary if section.section_summary else ""}

    ### {item.headline}
    **What happened:** {item.what_happened}
    **Why it matters:** {item.why_it_matters}
    **Takeaway:** _{item.key_takeaway}_
    {f"> 💡 {item.action_hint}" if item.action_hint else ""}
    🔗 [{item.headline}]({item.url}) · `{item.source}` · `{", ".join(item.tags)}`

    [repeat for each item in section]

    ---

    ## 🧠 Model Releases
    [same pattern]

    ## 🔧 New Tools
    [same pattern]

    ## 📄 Research Worth Noting
    [same pattern]

    ## ⚙️ Infrastructure
    [same pattern]

    ## 💬 Community Buzz
    [same pattern]

    ---

    ## 🔗 Quick Links

    | # | Title | Source | Tags | Sensitivity |
    |---|-------|--------|------|-------------|
    | 1 | [{item.headline}]({item.url}) | `{item.source}` | {tags} | {sensitivity} |
    [... one row per item ...]

    ---

    ## 📊 Today's Stats

    | Source | Selected | Reviewed | Drop Rate |
    |--------|----------|----------|-----------|
    | rss_feeds | 25 | 168 | 85% |
    | github | 15 | 46 | 67% |
    | hackernews | 5 | 9 | 44% |
    | huggingface | 5 | 40 | 87% |
    | arxiv | 3 | 298 | 99% |
    | semantic_scholar | 1 | 100 | 99% |
    | stackoverflow | 3 | 18 | 83% |
    | **TOTAL** | **57** | **679** | **92%** |

    _Generated {metadata.generated_at:%Y-%m-%d %H:%M} UTC
    · Providers: {", ".join(providers_used)}
    · Schema v{metadata.schema_version}_
    ──────────────────────────────────────────────────────────────────
    """
    content:         str  = Field(..., min_length=500)
    char_count:      int  = 0
    section_headers: list[str] = Field(default_factory=list)


class HTMLDigest(BaseModel):
    """
    Rendered HTML.
    SAFETY: ALL item fields (headline, what_happened, why_it_matters,
    key_takeaway, action_hint) MUST be html.escape()-d before injection.
    ALL urls MUST be validated via AnyHttpUrl before injecting as href.
    was_escaped=True is a required invariant — fail loudly if False.

    SECTION STRUCTURE:
      <html>
        <head><title>AI Digest {date}</title></head>
        <body>
          <header>
            <h1>🤖 AI/ML Daily Digest</h1>
            <p class="meta">{date} · {N} items from {M} reviewed</p>
          </header>
          <section id="top-story">
            <h2>🔥 Today's Top Story</h2>
            <article class="digest-item top">
              <h3><a href="{ESCAPED_URL}">{ESCAPED_HEADLINE}</a></h3>
              <p class="what"><strong>What happened:</strong> {ESCAPED_WHAT}</p>
              <p class="why"><strong>Why it matters:</strong> {ESCAPED_WHY}</p>
              <blockquote class="takeaway">{ESCAPED_TAKEAWAY}</blockquote>
              {<p class="action">💡 {ESCAPED_ACTION}</p> if action_hint}
              <footer><span class="source">{source}</span>
                      <time>{published_at}</time>
                      <span class="tags">{tags}</span></footer>
            </article>
          </section>
          <section id="framework-releases"> ... </section>
          <section id="model-releases"> ... </section>
          <section id="new-tools"> ... </section>
          <section id="research"> ... </section>
          <section id="infrastructure"> ... </section>
          <section id="community-buzz"> ... </section>
          <section id="stats"> <table> ... </table> </section>
        </body>
      </html>
    """
    content:     str  = Field(..., min_length=500)
    was_escaped: bool = True    # Must always be True — fail build if False
    char_count:  int  = 0


class PlainTextDigest(BaseModel):
    """
    Rendered plain text. Used for email / terminal output.

    PLAIN TEXT TEMPLATE:
    ══════════════════════════════════════════════════════
    AI/ML DAILY DIGEST — {metadata.digest_date}
    {metadata.total_selected} items | {metadata.total_raw_items} reviewed
    ══════════════════════════════════════════════════════

    TOP STORY
    ─────────
    {top_story.headline}
    What: {top_story.what_happened}
    Why:  {top_story.why_it_matters}
    TL;DR: {top_story.key_takeaway}
    {f"Do: {top_story.action_hint}" if top_story.action_hint else ""}
    Link: {top_story.url}

    FRAMEWORK RELEASES ({n} items)
    ──────────────────────────────
    1. {item.headline}
       What: {item.what_happened}
       Why:  {item.why_it_matters}
       TL;DR: {item.key_takeaway}
       {f"Do: {item.action_hint}" if item.action_hint else ""}
       Link: {item.url}
       Tags: {", ".join(item.tags)}

    [sections continue in same format...]

    QUICK LINKS
    ───────────
    • {item.headline} [{item.source}] → {item.url}
    [one line per item]

    STATS
    ─────
    rss_feeds: 25/168 | github: 15/46 | hackernews: 5/9
    huggingface: 5/40 | arxiv: 3/298 | semantic_scholar: 1/100
    stackoverflow: 3/18 | TOTAL: 57/679
    ══════════════════════════════════════════════════════
    """
    content:    str = Field(..., min_length=200)
    char_count: int = 0
    line_count: int = 0


# ─────────────────────────────────────────────────────────────────────────────
# 4F.  COMBINED RENDER OUTPUT
# ─────────────────────────────────────────────────────────────────────────────

class DigestRenderOutput(BaseModel):
    """
    Final output of the output_node.
    All three formats committed to /digests/YYYY-MM-DD/ in GitHub repo.
    """
    schema_data:      FinalDigestSchema
    markdown:         MarkdownDigest
    html:             HTMLDigest
    plain_text:       PlainTextDigest
    render_timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
