"""
MCP client for calling tools on a FastMCP / Prefect Horizon server.

Architecture
------------
When deployed on Prefect Horizon, FastMCP servers expose the **MCP JSON-RPC
protocol** at POST /mcp, NOT a plain REST API.  This means endpoints like
`POST /fetch/rss` do NOT exist on Horizon; instead you must call the tool
via the MCP protocol:

    POST /mcp
    Accept: application/json, text/event-stream
    {"jsonrpc":"2.0","method":"tools/call","params":{"name":"<tool>","arguments":{...}},"id":1}

The server responds with an SSE stream whose `data:` line contains the JSON result.

Tool names are auto-generated by FastMCP from the FastAPI router paths:
  /fetch/rss          -> fetch_rss_fetch_rss_post
  /fetch/arxiv        -> fetch_arxiv_fetch_arxiv_post
  /fetch/github       -> fetch_github_fetch_github_post
  /fetch/hackernews   -> fetch_hackernews_fetch_hackernews_post
  /fetch/huggingface  -> fetch_huggingface_fetch_huggingface_post
  /fetch/stackoverflow-> fetch_stackoverflow_fetch_stackoverflow_post
  /fetch/reddit       -> fetch_reddit_fetch_reddit_post

Local fallback (uvicorn)
------------------------
When MCP_SERVER_URL points to a local uvicorn server (http://127.0.0.1:*),
the FastAPI REST endpoints at /fetch/* are available directly.
The client auto-detects which mode to use based on the URL.
"""

from __future__ import annotations

import json
import re
from typing import Any, Dict, Optional

import httpx

from ..config.settings import settings

# Map REST path suffix -> MCP tool name (Horizon / FastMCP auto-generated names)
_TOOL_NAME_MAP: Dict[str, str] = {
    "/fetch/rss":           "fetch_rss_fetch_rss_post",
    "/fetch/arxiv":         "fetch_arxiv_fetch_arxiv_post",
    "/fetch/github":        "fetch_github_fetch_github_post",
    "/fetch/hackernews":    "fetch_hackernews_fetch_hackernews_post",
    "/fetch/huggingface":   "fetch_huggingface_fetch_huggingface_post",
    "/fetch/stackoverflow": "fetch_stackoverflow_fetch_stackoverflow_post",
    "/fetch/reddit":        "fetch_reddit_fetch_reddit_post",
}

_SSE_DATA_RE = re.compile(r"^data:\s*(.+)$", re.MULTILINE)


def _is_local(base_url: str) -> bool:
    """Return True if the URL points to a local/loopback server."""
    return "127.0.0.1" in base_url or "localhost" in base_url


def _normalize_base(raw_url: str) -> str:
    """
    Strip trailing slash and /mcp suffix so both of these work identically:
      - https://host.fastmcp.app
      - https://host.fastmcp.app/mcp
    """
    url = raw_url.rstrip("/")
    if url.endswith("/mcp"):
        url = url[:-4].rstrip("/")
    return url


def _call_via_mcp_protocol(
    base: str,
    tool_name: str,
    arguments: Dict[str, Any],
    token: Optional[str],
    timeout: float,
) -> Dict[str, Any]:
    """
    Call a tool on a Horizon-hosted FastMCP server using the MCP JSON-RPC protocol.
    The server responds with an SSE stream; we parse the first `data:` line.
    """
    url = f"{base}/mcp"
    headers: Dict[str, str] = {
        "Content-Type": "application/json",
        # MCP servers REQUIRE both Accept types; omitting text/event-stream → 406
        "Accept": "application/json, text/event-stream",
    }
    if token:
        headers["Authorization"] = f"Bearer {token}"

    payload = {
        "jsonrpc": "2.0",
        "method": "tools/call",
        "params": {
            "name": tool_name,
            "arguments": arguments,
        },
        "id": 1,
    }

    with httpx.Client(timeout=timeout, follow_redirects=True) as client:
        resp = client.post(url, json=payload, headers=headers)
        resp.raise_for_status()

    # Parse SSE response — find the first `data: {...}` line
    raw_text = resp.text
    match = _SSE_DATA_RE.search(raw_text)
    if not match:
        raise ValueError(f"MCP server returned no data line in SSE response: {raw_text[:300]}")

    envelope = json.loads(match.group(1))

    # Check for JSON-RPC level errors
    if "error" in envelope:
        err = envelope["error"]
        raise RuntimeError(f"MCP tool error [{err.get('code')}]: {err.get('message')}")

    result = envelope.get("result", {})

    # FastMCP wraps the tool output inside result.content[0].text as a JSON string
    content = result.get("content", [])
    if content and isinstance(content, list):
        first = content[0]
        if isinstance(first, dict) and first.get("type") == "text":
            return json.loads(first["text"])

    # If result is already a dict (some FastMCP versions return directly), use it
    if isinstance(result, dict) and result:
        return result

    raise ValueError(f"Could not extract tool result from MCP response: {str(result)[:300]}")


def _call_via_rest(
    base: str,
    path_suffix: str,
    json_body: Dict[str, Any],
    token: Optional[str],
    timeout: float,
) -> Dict[str, Any]:
    """
    Call a local uvicorn FastAPI server via plain REST POST.
    Used when MCP_SERVER_URL points to localhost / 127.0.0.1.
    """
    path = path_suffix if path_suffix.startswith("/") else f"/{path_suffix}"
    url = f"{base}{path}"
    headers: Dict[str, str] = {"Content-Type": "application/json"}
    if token:
        headers["Authorization"] = f"Bearer {token}"

    with httpx.Client(timeout=timeout, follow_redirects=True) as client:
        resp = client.post(url, json=json_body, headers=headers)
        resp.raise_for_status()
        return resp.json()


def post_fetch(
    path_suffix: str,
    json_body: Dict[str, Any],
    *,
    bearer_token: Optional[str] = None,
    timeout: Optional[float] = None,
) -> Dict[str, Any]:
    """
    Unified entry point for all subgraphs.

    Automatically selects the correct transport:
    - Local server  → plain REST POST to /fetch/<source>
    - Horizon cloud → MCP JSON-RPC tools/call to /mcp

    path_suffix examples: '/fetch/rss', '/fetch/arxiv'
    """
    raw_base = str(settings.mcp_base_url)
    base = _normalize_base(raw_base)
    token = bearer_token if bearer_token is not None else settings.mcp_bearer_token
    t = timeout if timeout is not None else settings.mcp_request_timeout_seconds

    # Normalize path_suffix
    path = path_suffix if path_suffix.startswith("/") else f"/{path_suffix}"

    if _is_local(base):
        # Local uvicorn: use fast plain REST endpoints
        return _call_via_rest(base, path, json_body, token, t)
    else:
        # Horizon cloud: use MCP JSON-RPC protocol
        tool_name = _TOOL_NAME_MAP.get(path)
        if not tool_name:
            raise ValueError(
                f"No MCP tool name mapping found for path '{path}'. "
                f"Known paths: {list(_TOOL_NAME_MAP.keys())}"
            )
        return _call_via_mcp_protocol(base, tool_name, json_body, token, t)
